#!/usr/bin/env bash
# Agent CI workflow installer
# Usage: GH_PAT=<token> curl -sL https://raw.githubusercontent.com/youngrok-XCENA/relay/main/install.sh | bash

set -euo pipefail

VERSION="1.0.0"
RUNNER_BASE="$HOME/actions-runners"
AVAILABLE_AGENTS=""
CI_REPO="youngrok-XCENA/relay"

# ─── Output helpers ───

use_color=false
if [ -t 1 ] && command -v tput &>/dev/null && [ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]; then
  use_color=true
fi

ok()   { if $use_color; then printf '\033[32m✓\033[0m %s\n' "$1"; else printf '  OK: %s\n' "$1"; fi; }
err()  { if $use_color; then printf '\033[31m✗\033[0m %s\n' "$1" >&2; else printf '  FAIL: %s\n' "$1" >&2; fi; }
info() { if $use_color; then printf '\033[34m→\033[0m %s\n' "$1"; else printf '  %s\n' "$1"; fi; }

# ─── Dependency checks ───

check_deps() {
  local missing=false

  for cmd in git gh jq; do
    if ! command -v "$cmd" &>/dev/null; then
      err "$cmd 이 설치되어 있지 않습니다."
      missing=true
    fi
  done

  if $missing; then
    echo "" >&2
    echo "필요한 도구를 먼저 설치하세요:" >&2
    echo "  git: https://git-scm.com" >&2
    echo "  gh:  https://cli.github.com" >&2
    echo "  jq:  sudo apt install jq" >&2
    exit 1
  fi
}

# ─── Agent auth detection ───

detect_available_agents() {
  AVAILABLE_AGENTS=""

  if command -v claude &>/dev/null && [ -f "$HOME/.claude/.credentials.json" ] \
     && jq -e '.claudeAiOauth.accessToken' "$HOME/.claude/.credentials.json" &>/dev/null; then
    AVAILABLE_AGENTS="claude"
    ok "Claude 인증 확인됨"
  else
    info "Claude 미설치 또는 미인증 — 건너뜀"
  fi

  if command -v codex &>/dev/null && [ -f "$HOME/.codex/auth.json" ] \
     && jq -e '.tokens' "$HOME/.codex/auth.json" &>/dev/null; then
    AVAILABLE_AGENTS="$AVAILABLE_AGENTS codex"
    ok "Codex 인증 확인됨"
  else
    info "Codex 미설치 또는 미인증 — 건너뜀"
  fi

  AVAILABLE_AGENTS=$(echo "$AVAILABLE_AGENTS" | xargs)

  if [ -z "$AVAILABLE_AGENTS" ]; then
    err "인증된 AI agent가 없습니다."
    echo "" >&2
    echo "Claude 또는 Codex 중 하나 이상 설치하고 로그인하세요:" >&2
    echo "  claude: https://docs.anthropic.com/en/docs/claude-code" >&2
    echo "  codex:  https://github.com/openai/codex" >&2
    exit 1
  fi
}

# ─── Git helpers ───

detect_git_root() {
  git -C "$1" rev-parse --show-toplevel 2>/dev/null
}

parse_github_repo_from_remote() {
  local remote_url="$1" repo
  repo=$(printf '%s\n' "$remote_url" | sed -nE 's#^(git@github\.com:|ssh://git@github\.com/|https://github\.com/|http://github\.com/)([^[:space:]]+)$#\2#p')
  [ -n "$repo" ] || return 1
  repo="${repo%.git}"
  repo="${repo%/}"
  printf '%s\n' "$repo"
}

detect_current_repo() {
  local start_dir="$1" git_root remote_url repo

  git_root=$(detect_git_root "$start_dir") || {
    err "git repository 안에서 실행해 주세요."
    exit 1
  }

  remote_url=$(git -C "$git_root" remote get-url origin 2>/dev/null || true)
  if [ -z "$remote_url" ]; then
    err "origin remote를 먼저 설정하세요."
    exit 1
  fi

  repo=$(parse_github_repo_from_remote "$remote_url") || {
    err "origin이 GitHub repository가 아닙니다: $remote_url"
    exit 1
  }

  printf '%s\n' "$repo"
}

detect_base_branch() {
  local repo="$1" branch
  branch=$(gh api "repos/$repo" --jq '.default_branch' 2>/dev/null || true)
  if [ -z "$branch" ]; then
    branch="main"
    info "기본 브랜치를 감지하지 못했습니다. main을 사용합니다."
  fi
  printf '%s\n' "$branch"
}

# ─── Workflow generators ───

version_stamp() {
  echo "# Generated by $CI_REPO/install.sh v${VERSION}"
}

generate_claude() {
  local desc="$1" style="$2" exts="$3" build="$4" test_cmd="$5" base="$6"
  version_stamp
  cat <<EOF
name: Claude CI
on:
  issues:
    types: [opened, reopened, closed, labeled]
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
permissions:
  contents: write
  issues: write
  pull-requests: write
jobs:
  review:
    if: >
      startsWith(github.event.comment.body, '/claude-review') &&
      (github.event_name == 'pull_request_review_comment' || github.event.issue.pull_request)
    uses: youngrok-XCENA/relay/.github/workflows/claude.yml@main
    with:
      mode: review
      project_description: "$desc"
      code_style_guide: "$style"
      file_extensions: "$exts"
      max_review_turns: 10
      timeout_minutes: 15
    secrets:
      GH_PAT: \${{ secrets.GH_PAT }}

  fix:
    if: >
      github.event_name == 'issue_comment' &&
      !github.event.issue.pull_request &&
      startsWith(github.event.comment.body, '/claude-fix')
    uses: youngrok-XCENA/relay/.github/workflows/claude.yml@main
    with:
      mode: fix
      project_description: "$desc"
      build_command: "$build"
      test_command: "$test_cmd"
      code_style_guide: "$style"
      base_branch: "$base"
      timeout_minutes: 30
    secrets:
      GH_PAT: \${{ secrets.GH_PAT }}

  pr-fix:
    if: >
      github.event_name == 'issue_comment' &&
      github.event.issue.pull_request &&
      startsWith(github.event.comment.body, '/claude-fix')
    uses: youngrok-XCENA/relay/.github/workflows/claude.yml@main
    with:
      mode: pr-fix
      project_description: "$desc"
      code_style_guide: "$style"
      timeout_minutes: 30
    secrets:
      GH_PAT: \${{ secrets.GH_PAT }}

  triage:
    if: >
      (github.event_name == 'issues' &&
       (github.event.action == 'closed' ||
        (contains(github.event.issue.title, 'claude') && !contains(github.event.issue.title, 'claude-auto')))) ||
      (github.event_name == 'issue_comment' &&
       !github.event.issue.pull_request &&
       startsWith(github.event.comment.body, '/claude-issue') &&
       github.event.comment.user.type != 'Bot' &&
       github.event.sender.login != 'github-actions[bot]')
    uses: youngrok-XCENA/relay/.github/workflows/claude.yml@main
    with:
      mode: triage
      project_description: "$desc"
      trigger_command: "/claude-issue"
      title_keyword: "claude"
      max_turns: 15
      timeout_minutes: 20
    secrets:
      GH_PAT: \${{ secrets.GH_PAT }}

  auto-pipeline:
    if: >
      (github.event_name == 'issues' &&
       github.event.action == 'labeled' &&
       github.event.label.name == 'auto-fix') ||
      (github.event_name == 'issues' &&
       (github.event.action == 'opened' || github.event.action == 'reopened') &&
       contains(github.event.issue.title, 'claude-auto'))
    uses: youngrok-XCENA/relay/.github/workflows/claude.yml@main
    with:
      mode: auto-pipeline
      project_description: "$desc"
      code_style_guide: "$style"
      file_extensions: "$exts"
      timeout_minutes: 60
    secrets:
      GH_PAT: \${{ secrets.GH_PAT }}
EOF
}

generate_codex() {
  local desc="$1" style="$2" exts="$3" build="$4" test_cmd="$5" base="$6"
  version_stamp
  cat <<EOF
name: Codex
on:
  issues:
    types: [opened, reopened, closed, labeled]
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
permissions:
  contents: write
  issues: write
  pull-requests: write
jobs:
  review:
    if: >
      startsWith(github.event.comment.body, '/codex-review') &&
      (
        github.event_name == 'pull_request_review_comment' ||
        (github.event_name == 'issue_comment' && github.event.issue.pull_request)
      )
    uses: youngrok-XCENA/relay/.github/workflows/codex.yml@main
    with:
      mode: review
      project_description: "$desc"
      code_style_guide: "$style"
      file_extensions: "$exts"
      codex_sandbox: "read-only"
      timeout_minutes: 15
    secrets:
      GH_PAT: \${{ secrets.GH_PAT }}

  fix:
    if: >
      github.event_name == 'issue_comment' &&
      !github.event.issue.pull_request &&
      startsWith(github.event.comment.body, '/codex-fix')
    uses: youngrok-XCENA/relay/.github/workflows/codex.yml@main
    with:
      mode: fix
      project_description: "$desc"
      build_command: "$build"
      test_command: "$test_cmd"
      code_style_guide: "$style"
      base_branch: "$base"
      codex_sandbox: "full-auto"
      timeout_minutes: 30
    secrets:
      GH_PAT: \${{ secrets.GH_PAT }}

  triage:
    if: >
      (github.event_name == 'issues' &&
       (
         github.event.action == 'closed' ||
         (
           (github.event.action == 'opened' || github.event.action == 'reopened') &&
           contains(github.event.issue.title, 'codex') &&
           !contains(github.event.issue.title, 'codex-auto')
         )
       )) ||
      (github.event_name == 'issue_comment' &&
       !github.event.issue.pull_request &&
       startsWith(github.event.comment.body, '/codex-issue') &&
       github.event.comment.user.type != 'Bot' &&
       github.event.sender.login != 'github-actions[bot]')
    uses: youngrok-XCENA/relay/.github/workflows/codex.yml@main
    with:
      mode: triage
      project_description: "$desc"
      trigger_command: "/codex-issue"
      title_keyword: "codex"
      auto_title_keyword: "codex-auto"
      codex_sandbox: "read-only"
      timeout_minutes: 20
    secrets:
      GH_PAT: \${{ secrets.GH_PAT }}

  auto-pipeline:
    if: >
      github.event_name == 'issues' &&
      (
        (
          (github.event.action == 'opened' || github.event.action == 'reopened') &&
          contains(github.event.issue.title, 'codex-auto')
        ) ||
        (
          github.event.action == 'labeled' &&
          github.event.label.name == 'auto-fix'
        )
      )
    uses: youngrok-XCENA/relay/.github/workflows/codex.yml@main
    with:
      mode: auto-pipeline
      project_description: "$desc"
      code_style_guide: "$style"
      file_extensions: "$exts"
      auto_title_keyword: "codex-auto"
      codex_sandbox: "full-auto"
      timeout_minutes: 60
    secrets:
      GH_PAT: \${{ secrets.GH_PAT }}
EOF
}

generate_schedule() {
  local agent="$1"
  version_stamp
  cat <<SEOF
# 스케줄 CI (${agent}) — 주석을 해제하고 프로젝트에 맞게 수정하세요.
#
# name: Scheduled CI (${agent})
# on:
#   schedule:
#     - cron: '0 18 * * *'   # UTC 18:00 = KST 03:00
#   workflow_dispatch:        # 수동 실행도 가능
# permissions:
#   contents: write
#   issues: write
#   pull-requests: write
# env:
#   GH_TOKEN: \${{ secrets.GH_PAT }}
# jobs:
#   create-issue:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Create scheduled issue
#         shell: bash
#         env:
#           REPO: \${{ github.repository }}
#         run: |
#           ISSUE_DATE="\$(TZ=Asia/Seoul date +%F)"
#           TITLE="${agent}-auto 설계 개선 \${ISSUE_DATE}"
#
#           # 같은 날 이미 생성된 이슈가 있으면 스킵
#           EXISTING=\$(gh issue list --repo "\$REPO" --state open \\
#             --search "in:title \\"\$TITLE\\"" --json number --jq '.[0].number // empty')
#           if [ -n "\$EXISTING" ]; then
#             echo "이미 존재: #\${EXISTING}"
#             exit 0
#           fi
#
#           gh issue create --repo "\$REPO" \\
#             --title "\$TITLE" \\
#             --body "현재 코드에서 가장 가치 있는 설계 개선 하나를 골라 수정해 주세요."
SEOF
}

# ─── Workflow helpers ───

caller_filename_for_workflow() {
  case "$1" in
    claude) echo "claude-caller.yml" ;;
    codex)  echo "codex-caller.yml" ;;
    *)      echo "${1}-caller.yml" ;;
  esac
}

list_stale_caller_files() {
  printf '%s\n' \
    "code-style-caller.yml" \
    "cppcheck-caller.yml" \
    "yr-claude.yml" \
    "yr-claude-review.yml" \
    "yr-claude-fix.yml" \
    "yr-claude-issue-triage.yml" \
    "yr-claude-auto-pipeline.yml" \
    "yr-codex.yml" \
    "yr-codex-review.yml" \
    "yr-codex-fix.yml" \
    "yr-codex-issue-triage.yml" \
    "yr-codex-auto-pipeline.yml" \
    "yr-code-style.yml" \
    "yr-cppcheck.yml"
}

cleanup_stale_local_workflows() {
  local output_dir="$1"
  while IFS= read -r filename; do
    [ -n "$filename" ] || continue
    local path="$output_dir/.github/workflows/$filename"
    if [ -f "$path" ]; then
      rm -f "$path"
      ok "오래된 파일 제거: $filename"
    fi
  done < <(list_stale_caller_files)
}

render_workflow_content() {
  local workflow="$1" desc="$2" style="$3" exts="$4" build="$5" test_cmd="$6" base="$7"
  case "$workflow" in
    claude) generate_claude "$desc" "$style" "$exts" "$build" "$test_cmd" "$base" ;;
    codex)  generate_codex  "$desc" "$style" "$exts" "$build" "$test_cmd" "$base" ;;
    *)      return 1 ;;
  esac
}

# ─── Install steps ───

install_workflows() {
  local repo_root="$1" repo="$2" base="$3"
  local desc style exts build test_cmd
  local workflow_dir="$repo_root/.github/workflows"

  desc=""
  style=""
  exts=""
  build=""
  test_cmd=""

  mkdir -p "$workflow_dir"

  for wf in $AVAILABLE_AGENTS; do
    local filename filepath content
    filename=$(caller_filename_for_workflow "$wf")
    filepath="$workflow_dir/$filename"
    content=$(render_workflow_content "$wf" "$desc" "$style" "$exts" "$build" "$test_cmd" "$base")
    printf '%s' "$content" > "$filepath"
    ok "$filename 생성"
  done

  # agent별 schedule yml 생성 (없을 때만 — 사용자가 수정했을 수 있으므로)
  for agent in $AVAILABLE_AGENTS; do
    local schedule_path="$workflow_dir/${agent}-schedule.yml"
    if [ ! -f "$schedule_path" ]; then
      generate_schedule "$agent" > "$schedule_path"
      ok "${agent}-schedule.yml 생성 (주석 해제 후 사용)"
    else
      ok "${agent}-schedule.yml 이미 존재 — 건너뜀"
    fi
  done

  cleanup_stale_local_workflows "$repo_root"
}

install_secret() {
  local repo="$1"

  if gh secret list -R "$repo" 2>/dev/null | grep -q '^GH_PAT'; then
    ok "GH_PAT secret 이미 설정됨"
    return
  fi

  local clean_pat
  clean_pat="$(printf '%s' "$GH_PAT" | tr -d '\r\n')"
  printf '%s' "$clean_pat" | gh secret set GH_PAT -R "$repo"
  ok "GH_PAT secret 설정 완료"
}

remove_runner() {
  local runner_dir="$1" repo="$2" runner_type="$3"

  if [ ! -d "$runner_dir" ]; then
    return
  fi

  # 실행 중인 runner 프로세스 종료
  if [ -f "$runner_dir/.runner" ]; then
    local runner_pid
    runner_pid=$(pgrep -f "$runner_dir/bin/Runner.Listener" 2>/dev/null || true)
    if [ -n "$runner_pid" ]; then
      kill "$runner_pid" 2>/dev/null || true
      info "$runner_type runner 프로세스 종료 (PID: $runner_pid)"
    fi

    # GitHub에서 등록 해제
    local remove_token
    remove_token=$(gh api "repos/$repo/actions/runners/remove-token" -X POST --jq '.token' 2>/dev/null || true)
    if [ -n "$remove_token" ]; then
      "$runner_dir/config.sh" remove --token "$remove_token" 2>/dev/null || true
      ok "$runner_type runner 등록 해제 완료"
    fi
  fi

  rm -rf "$runner_dir"
  ok "$runner_type runner 디렉토리 제거 완료"
}

install_runners() {
  local repo="$1"
  local repo_name
  repo_name=$(basename "$repo")

  local runner_tar="$RUNNER_BASE/actions-runner-linux-x64.tar.gz"
  if [ ! -f "$runner_tar" ]; then
    info "GitHub Actions runner 바이너리 다운로드 중..."
    mkdir -p "$RUNNER_BASE"
    local runner_version
    runner_version=$(gh api repos/actions/runner/releases/latest --jq '.tag_name' | sed 's/^v//')
    curl -sL "https://github.com/actions/runner/releases/download/v${runner_version}/actions-runner-linux-x64-${runner_version}.tar.gz" \
      -o "$runner_tar"
    ok "Runner v${runner_version} 다운로드 완료"
  fi

  for runner_type in $AVAILABLE_AGENTS; do
    local runner_dir="$RUNNER_BASE/$repo/$runner_type"
    local label="${runner_type}-ci"
    local name="${runner_type}-ci-runner-${repo_name}"

    # 기존 runner 제거 후 새로 설치
    remove_runner "$runner_dir" "$repo" "$runner_type"

    info "$runner_type runner 설정 중..."
    mkdir -p "$runner_dir"
    tar xzf "$runner_tar" -C "$runner_dir"

    local token
    token=$(gh api "repos/$repo/actions/runners/registration-token" -X POST --jq '.token')

    "$runner_dir/config.sh" \
      --url "https://github.com/$repo" \
      --token "$token" \
      --name "$name" \
      --labels "self-hosted,$label" \
      --unattended

    nohup "$runner_dir/run.sh" > "$runner_dir/runner.log" 2>&1 &
    ok "$runner_type runner 시작 (PID: $!)"
  done
}

# ─── Main ───

main() {
  if [ "${1:-}" = "--help" ] || [ "${1:-}" = "-h" ]; then
    cat <<EOF
사용법:
  GH_PAT=<token> bash install.sh

GitHub repo에 Claude/Codex AI agent CI workflow를 설치합니다.

  1. workflow 파일 생성 (.github/workflows/)
  2. GH_PAT secret 설정
  3. self-hosted runner 등록 (claude-ci, codex-ci)

GH_PAT 생성: GitHub > Settings > Developer settings > Personal access tokens
필요 권한: repo, workflow
EOF
    exit 0
  fi

  # GH_PAT 필수
  if [ -z "${GH_PAT:-}" ]; then
    err "GH_PAT 환경변수가 설정되지 않았습니다."
    echo "" >&2
    echo "GH_PAT를 먼저 생성하세요:" >&2
    echo "  1. https://github.com/settings/tokens 에서 Personal Access Token 생성" >&2
    echo "  2. 필요 권한: repo, workflow" >&2
    echo "" >&2
    echo "사용법:" >&2
    echo "  GH_PAT=ghp_xxxx bash install.sh" >&2
    exit 1
  fi

  check_deps
  detect_available_agents

  # Git repo 감지
  local repo_root repo base
  repo_root=$(detect_git_root ".") || {
    err "git repository 안에서 실행해 주세요."
    exit 1
  }
  repo=$(detect_current_repo "$repo_root")

  # CI repo 자체 가드
  if [ "$repo" = "$CI_REPO" ]; then
    err "이 스크립트는 $CI_REPO 안에서 실행할 수 없습니다."
    echo "  agent CI를 설치할 caller repo에서 실행하세요." >&2
    exit 1
  fi

  echo ""
  info "설치 대상: $repo"
  echo ""

  # base branch 자동 감지
  base=$(detect_base_branch "$repo")
  info "기본 브랜치: $base"
  echo ""

  # 1. Workflow 파일 생성
  info "[1/3] Workflow 파일 생성"
  install_workflows "$repo_root" "$repo" "$base"
  echo ""

  # 2. GH_PAT secret 설정
  info "[2/3] GH_PAT secret 설정"
  install_secret "$repo"
  echo ""

  # 3. Runner 등록
  info "[3/3] Self-hosted runner 등록"
  install_runners "$repo"
  echo ""

  # 완료
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  ok "설치 완료: $repo"
  echo ""
  echo "프로젝트에 맞게 설정하세요:"
  for wf in $AVAILABLE_AGENTS; do
    local filename
    filename=$(caller_filename_for_workflow "$wf")
    echo "  .github/workflows/$filename"
  done
  echo ""
  echo "  설정 가능 항목:"
  echo "    project_description  — 프로젝트 설명 (AI 컨텍스트)"
  echo "    build_command        — 빌드 명령 (fix 후 검증)"
  echo "    test_command         — 테스트 명령 (fix 후 검증)"
  echo "    code_style_guide     — 코딩 스타일 가이드"
  echo "    file_extensions      — 리뷰 대상 파일 패턴"
  echo ""
  echo "스케줄 CI (선택):"
  for agent in $AVAILABLE_AGENTS; do
    echo "  .github/workflows/${agent}-schedule.yml"
  done
  echo "  주석을 해제하면 매일 지정 시각에 자동으로 개선 이슈를 생성합니다."
  echo ""
  echo "커밋 & 푸시:"
  echo "  git add .github/workflows/"
  echo "  git commit -m 'ci: add agent CI workflows'"
  echo "  git push"
  echo ""
  echo "설치 검증:"
  echo "  curl -sL https://raw.githubusercontent.com/$CI_REPO/main/verify.sh | bash"
  echo ""
  echo "파이프라인 테스트:"
  local first_agent
  first_agent=$(echo "$AVAILABLE_AGENTS" | awk '{print $1}')
  echo "  gh issue create --title \"${first_agent}-auto 첫 번째 개선\" --body \"현재 코드에서 가장 가치 있는 개선 하나를 골라 수정해 주세요.\""
}

main "$@"
