#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
INSTALL_SH="$REPO_ROOT/install.sh"

assert_file_exists() {
  if [ ! -f "$1" ]; then
    echo "expected file to exist: $1" >&2
    exit 1
  fi
}

assert_contains() {
  if [[ "$1" != *"$2"* ]]; then
    echo "missing expected content: $2" >&2
    exit 1
  fi
}

# Source install.sh functions (everything before main)
TMP_INSTALL="$(mktemp)"
trap 'rm -f "$TMP_INSTALL"' EXIT

sed '/^main "\$@"$/d' "$INSTALL_SH" | sed '/^main() {$/,/^}$/d' > "$TMP_INSTALL"

# shellcheck disable=SC1090
source "$TMP_INSTALL"

TMP_DIR="$(mktemp -d)"
trap 'rm -f "$TMP_INSTALL"; rm -rf "$TMP_DIR"' EXIT

git -C "$TMP_DIR" init -q
git -C "$TMP_DIR" remote add origin git@github.com:youngrok-XCENA/example.git
AVAILABLE_AGENTS="claude codex"

install_workflows "$TMP_DIR" "youngrok-XCENA/example" "main" >/dev/null

CLAUDE_CALLER="$TMP_DIR/.github/workflows/relay-claude.yml"
CODEX_CALLER="$TMP_DIR/.github/workflows/relay-codex.yml"

assert_file_exists "$CLAUDE_CALLER"
assert_file_exists "$CODEX_CALLER"

CLAUDE_CONTENT="$(cat "$CLAUDE_CALLER")"
assert_contains "$CLAUDE_CONTENT" 'project_description: ""'
assert_contains "$CLAUDE_CONTENT" 'uses: youngrok-XCENA/relay/.github/workflows/relay.yml@main'
assert_contains "$CLAUDE_CONTENT" '# Generated by youngrok-XCENA/relay/install.sh'

echo "ok"
