#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
INSTALL_SH="$REPO_ROOT/install.sh"

assert_contains() {
  if [[ "$1" != *"$2"* ]]; then
    echo "missing expected content: $2" >&2
    exit 1
  fi
}

# Source install.sh functions (everything before main)
TMP_INSTALL="$(mktemp)"
trap 'rm -f "$TMP_INSTALL"' EXIT

sed '/^main "\$@"$/d' "$INSTALL_SH" | sed '/^main() {$/,/^}$/d' > "$TMP_INSTALL"

# shellcheck disable=SC1090
source "$TMP_INSTALL"

CLAUDE_CONTENT="$(generate_relay_caller claude "Test" "" "*.py" "" "" "main")"
CODEX_CONTENT="$(generate_relay_caller codex "Test" "" "*.py" "" "" "main")"

assert_contains "$CLAUDE_CONTENT" "# Generated by youngrok-XCENA/relay/install.sh v"
assert_contains "$CODEX_CONTENT" "# Generated by youngrok-XCENA/relay/install.sh v"

# Version stamp should be the first line
FIRST_LINE_CLAUDE="$(echo "$CLAUDE_CONTENT" | head -1)"
FIRST_LINE_CODEX="$(echo "$CODEX_CONTENT" | head -1)"

assert_contains "$FIRST_LINE_CLAUDE" "# Generated by"
assert_contains "$FIRST_LINE_CODEX" "# Generated by"

echo "ok"
