#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
INSTALL_SH="$REPO_ROOT/install.sh"

assert_file_exists() {
  if [ ! -f "$1" ]; then
    echo "expected file to exist: $1" >&2
    exit 1
  fi
}

assert_not_exists() {
  if [ -e "$1" ]; then
    echo "expected path to be removed: $1" >&2
    exit 1
  fi
}

assert_contains() {
  if [[ "$1" != *"$2"* ]]; then
    echo "missing expected content: $2" >&2
    exit 1
  fi
}

# Source install.sh functions (everything before main)
TMP_INSTALL="$(mktemp)"
TMP_DIR="$(mktemp -d)"
trap 'rm -f "$TMP_INSTALL"; rm -rf "$TMP_DIR"' EXIT

sed '/^main "\$@"$/d' "$INSTALL_SH" | sed '/^main() {$/,/^}$/d' > "$TMP_INSTALL"

# shellcheck disable=SC1090
source "$TMP_INSTALL"

git -C "$TMP_DIR" init -q
git -C "$TMP_DIR" remote add origin git@github.com:youngrok-XCENA/local-test.git
mkdir -p "$TMP_DIR/.github/workflows"
touch "$TMP_DIR/.github/workflows/yr-claude.yml"
touch "$TMP_DIR/.github/workflows/code-style-caller.yml"

install_workflows "$TMP_DIR" "youngrok-XCENA/local-test" "main" >/dev/null

CLAUDE_CALLER="$TMP_DIR/.github/workflows/claude-caller.yml"
CODEX_CALLER="$TMP_DIR/.github/workflows/codex-caller.yml"

assert_file_exists "$CLAUDE_CALLER"
assert_file_exists "$CODEX_CALLER"
assert_not_exists "$TMP_DIR/.github/workflows/yr-claude.yml"
assert_not_exists "$TMP_DIR/.github/workflows/code-style-caller.yml"

CLAUDE_CONTENT="$(cat "$CLAUDE_CALLER")"
assert_contains "$CLAUDE_CONTENT" 'project_description: ""'
assert_contains "$CLAUDE_CONTENT" 'base_branch: "main"'
assert_contains "$CLAUDE_CONTENT" '# Generated by youngrok-XCENA/relay/install.sh'

echo "ok"
